### ISSUE TITLE
`yq` dependency conflicts with `go-yq` 

### ISSUE THREAD

**Issue by averyfreeman** [claui/aur-pull#1]
Hey, I am not sure if this is something that you can do, I think I saw somewhere people were talking about putting an `if:then` in their `PKGBUILD` because there isn't a more graceful way to deal with multiple options, like an (OR) statement (like a double-pipe `||` or anything like that)

Anyway, this is probably overkill for the issue, and the real issue might be upstream (PKGBUILD).  But if there's a way you can build an option for either `yq` or a drop-in, that would be awesome, and please tell me how it's done, because I've been trying to figure it out myself.

I removed `yq` from dependencies, but I assume that's not going to work for people who don't have a package that will do the same work.

Thanks,

b-report synopsis:
Possible to enable package build with alternative `yq`-compatible drop-in `go-yq`? 

expected result:
for `makepkg -s` to build `aur-pull` without interruption, either identifying or downloading dependencies as needed

actual result (process): 
1. `makepkg -s` began process of building the `aur-pull` package 
2. `makepkg` stopped due to missing dependency `yq` during check 
3. `yq` was identified as a conflicting with installed package `go-yq`
4. User aborted build process re: unwillingness to replace `go-yq` with `yq`

workaround:
1. `PKGBUILD` alteration options: 
- - (A) change dependency from `yq` to `go-yq` or
- - (B) remove `yq` from dependencies array
3. decided option (B) and removed `yq` from dependencies array
4. built `aur-pull` package without further complaint from `makepkg`
5. tested `aur-pull` functions for build incompatibility artifacts

Result: No noticed side-effects from building with `go-yq` instead of `yq`.

**Comment by claui** [comment]
Hey @averyfreeman,

thanks for reaching out.

I just checked out `go-yq` for a couple of minutes, and found a couple of minor incompatibilities that keep it from playing well with `aur-pull`.

My findings for now:

1. Unlike `yq`,`go-yq` doesn’t come with a `tomlq` executable. I’d have to change `settings.bash` slightly to accommodate that, i.e. detect whether `go-yq` is installed, and if so, invoke `yq -oy` instead of `tomlq -t`.

2. `aur-pull` depends on the `--arg` feature of `yq`. From what I’ve seen, `go-yq` doesn’t offer anything like it. To make this work, I’d have to make a few changes to `settings.bash`, i.e. remove the `// \$default_value` expression, check whether `yq` returns `null`, and if so, return the default value.

I’d be ok with adding a feature that checks which `yq` flavor is installed, and makes the correct invocation (`tomlq -t` or `yq -oy`. PRs welcome.

> workaround:
>
>    PKGBUILD alteration options:
>
>        (A) change dependency from yq to go-yq or
>        (B) remove yq from dependencies array

Removing the dependency is not really an option, because without them `aur pull` would fail at runtime.

However, I’d be willing to upload and maintain an `aur-pull-go-yq` package that contains an exact copy of `aur-pull`, just with the `depends` entry changed to `go-yq`. They can share a common `pkgbase` so it’s actually not much duplication.

**Comment by claui** [comment]
On second thought – I’d prefer ditching `yq` altogether and use `python-tomlkit` directly instead, the engine backing `yq`. `python-tomlkit` can be installed without conflicts so I’d strongly prefer that.

PR incoming.

**Comment by claui** [comment]
@averyfreeman Cut a new release v0.1.1 and uploaded a new version of the AUR package, which no longer depends on `yq`. Feel free to give it a try!

**Comment by averyfreeman** [comment]
Hi Claui, wow that was fast.

Paraphrasing:
>My findings: `go-yq` = no `tomlq`.  `settings.bash` would req mods:  `go-yq` ? `yq -oy` : `tomlq -t`

>However,
>`aur-pull --arg` == `yq`, != `go-yq`; if `settings.bash // \$default_value` + `$(yq -f0nse $TAR) == null >=< RET $TAR` (?)

I agree, dealing with two `jq-alike` dependencies for `aur-pull` undoubtedly an over-commitment to maintenance. especially when you can trade both to deal with a format easily a gazillion times more forgiving (assertion carefully quantified, of course, thanks to gazillionaire's AI - with gazillions of As and somewhere some Is eventually).

I am slightly attached to go-yq's flags spelling `-f0nse`, if I chose correctly (there may have been bias)

mm, tomlkit is the reason I have poetry. go, lib.
